main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Close-ups
    identifier: closeups
    weight: 20
  - name: Chad and the Sahel
    url: /sahel/
    parent: closeups
    weight: 21
  - name: Central Africa
    url: /central-africa/
    parent: closeups
    weight: 22
  - name: Middle East
    url: /middle-east/
    parent: closeups
    weight: 23
  - name: Papua New Guinea and the Pacific
    url: /pacific/
    parent: closeups
    weight: 24
  - name: Wide angle
    url: /wide-angle/
    weight: 30
  - name: Publications
    url: /publication/
    weight: 40
  - name: Research
    url: '#research'
    weight: 50
  - name: Assignments
    url: /assignments/
    weight: 60
  - name: CV
    url: /uploads/resume_laville.pdf
    weight: 70